platform: linux/amd64

when:
    event: [push]
    branch: [sec]
  
pipeline:
    build-api:
        image: golang
        pull: true
        environment:
            - WEBPORT=11337
            - WEBURL=0.0.0.0
            - DBHOST=database:5432
            - DBUSER=bookstore
            - DBPASSWD=bookstore
            - DBNAME=bookstore
        commands:
            - go get
            - go vet
            - go build -o api ./server.go

services:
    database:
        image: postgres
        pull: true
        environment:
            - POSTGRES_USER=bookstore
            - POSTGRES_PASSWORD=bookstore
            - POSTGRES_DB=bookstore